name: Ayobami Static web APP
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker image and Deploy to EC2 Instance
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: roybylon/kod:${{ github.sha }}

      - name: SSH into EC2 Instance and deploy Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.COMPILER_AWS_HOST }}
          username: ${{ secrets.COMPILER_AWS_USERNAME }}
          key: ${{ secrets.COMPILER_AWS_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop kod || true
            docker rm kod || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kod:${{ github.sha }}
            sudo docker run -d --name kod -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/kod:${{ github.sha }}

